### PR TITLE
fix: ToC not highlighting properly

### LINKED ISSUE #21: [BUG] The TOC doesn't highlight the current section of the page.
### Describe the bug

First of all, sorry if my English is not correct, my native language is Spanish. Well, as I said in the title the TOC isn't working properly. Depending on the content it just gets crazy. I have tested it in Firefox and Chrome and building the exampleSite, but it is still not working. I even tried the [demo](ublogger.netlify.app).

### Expected behavior

It should highlight the name of the current section, but it highlights any of the next sections. I don't know if there is some configuration I'm not considering, but I have checked the documentation and the config.toml that comes with the exampleSite and didn't find anything that can solve this.

### Screenshots

In the next screenshot (theme-documentation-built-in-shortcodes), the "Instagram" tag gets highlighted, but we are in the "gist" section.
image

### Build Environment

- OS: Windows 10
- Theme version/commit addce32
- Hugo version 0.80.0 (extended)

### Preview Environment

- OS: Windows 10
- Browsers: Chrome, Edge, Firefox

### Additional Information

I would send my code, but I've also tried using the exampleSite and even the [demo](ublogger.netlify.app) works this way.

### PR DESCRIPTION
**Pull request by noaione**
This PR should fix ToC not highlighting the correct header.
It also checks if there's any embedded gist markdown with `headerLink` since it's also affect the ToC.

I don't know what tools you use to generate the minifed version in `assets` folder so I ignored that for now.

resolve #21

### CODE REVIEW

**Comment by uPagge** [comment]
Unfortunately, your solution only corrects the situation for one topic of the article, but creates problems in others. 

For example, if you run exampleSite, then on the article

http: // localhost: 1313 / theme-documentation-content

clicking on 3-content-summaries in the TOC will not take you to this section the first time.

**Comment by uPagge** [comment]
Apparently, the introduction of various designs for articles made this script not working, and you need to invent something anew

**Comment by noaione** [comment]
I've adjusted the fix, please check it.
It's a little bit janky but it should highlight it properly now

**Comment by uPagge** [comment]
Unfortunately, the problem persists

**Comment by uPagge** [comment]
The first time you press the TOC, it does not go where it should

**Comment by uPagge** [comment]
But it seems correct to show where we are.

**Comment by uPagge** [comment]
This is what happens when I click on item 4.1 for the first time.

изображение

The second and subsequent times, everything is fine.

изображение

**Comment by uPagge** [comment]
And I found another strange feature. For some reason, if the title is not in English, then it does not mark it as active

изображение

изображение

**Comment by uPagge** [comment]
@noaione I would be very glad if you fix these problems, as I know JS rather poorly.

**Comment by noaione** [comment]
Yeah, I don't know how to fix that problem currently, but I think that's the (desktop) browser problem not rendering everything yet so the linking is broken.

**Comment by uPagge** [comment]
@noaione Hello again. I found where the cause of the problem was.

`$tocLinkElements[i].hash.slice(1) === $selHeader.id`

The fact is that if the title is not English, then there will be gibberish on the left side, and the condition is not met

Examples in the screenshot

изображение
изображение

And I would like you to appreciate our decision, or perhaps with new information would correct your changes.

We have replaced this condition with the following

`$tocLinkElements[i].hash.slice(1) === encodeURI($selHeader.id)`

And this solved the problem with another language

File: src/js/theme.js [hunk 1]
```diff
@@ -472,11 +472,27 @@ class Theme {
...
                 if (activeTocIndex !== -1) {
-                    $tocLinkElements[activeTocIndex].classList.add('active');
-                    let $parent = $tocLinkElements[activeTocIndex].parentElement;
-                    while ($parent !== $tocCore) {
-                        $parent.classList.add('has-active');
-                        $parent = $parent.parentElement.parentElement;
+                    const $selHeader = $headerLinkElements[activeTocIndex];
+                    let $selectedToC;
+                    for (let i = 0; i < $tocLinkElements.length; i++) {
+                        if ($tocLinkElements[i].hash.slice(1) === $selHeader.id) {
```
Comment (uPagge) [inline src/js/theme.js:478]: $tocLinkElements[i].hash.slice(1) === encodeURI($selHeader.id)

**Comment by noaione** [comment]
Adjusted code as requested

**Comment by uPagge** [comment]
@noaione Many thanks for the help
